News_Scraper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    ]

core/urls.py
from django.urls import path
from .views import (
    PythonView,
    RealPythonView,
    HomeView,
    BenchmarkView,
    BoardGamesGeekView,
    ArcheologyView,
    ToJuzByloView,
    ComputerWorldView,
    LiveScienceView,
    StatisticsView,
    LowcyGierView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('benchmark/', BenchmarkView.as_view(), name="benchmark"),
    path('bgg/', BoardGamesGeekView.as_view(), name="bgg"),
    path('archeology/', ArcheologyView.as_view(), name="archeology"),
    path('tojuzbylo/', ToJuzByloView.as_view(), name="tojuzbylo"),
    path('computerworld/', ComputerWorldView.as_view(), name="computer-world"),
    path('python/', PythonView.as_view(), name="python"),
    path('real-python/', RealPythonView.as_view(), name="real-python"),
    path('livescience/', LiveScienceView.as_view(), name="livescience"),
    path('lowcy-gier/', LowcyGierView.as_view(), name="lowcygier"),
    path('statistics/', StatisticsView.as_view(), name="statistics"),

    path('chart-1/', StatisticsView.get_all_article_pie_chart_data, name='chart-1'),
    path('chart-2/', StatisticsView.get_all_article_tab_chart_data, name='chart-2'),
    path('chart-3/', StatisticsView.get_top_en_word_chart_data, name='chart-3'),
    path('chart-4/', StatisticsView.get_top_pl_word_chart_data, name='chart-4'),

    ]

templates/archeology.html
{% extends 'base.html' %}

{% block title %}
<title>Zwiadowca Historii</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">

        <hr class="my-5">

        <!--Section: Magazine v.1-->
        <section class="wow fadeIn">

            <!--Section heading-->
            <h2 class="h1 text-center my-5 font-weight-bold">Zwiadowca Historii - Tasty News</h2>

            <!--Grid row-->
            <div class="row text-left">

                <!--Grid column-->
                <div class="col-lg-6 col-md-12 h-100">

                    {% for element in data %}
                    <!--Small news-->
                    <div class="row">
                        <div class="col-md-3">

                            <!--Image-->
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid" alt="Minor sample post image">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>

                        <!--Excerpt-->
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>

                        </div>

                    </div>
                    <!--/Small news-->

                    <hr>
                    {% endfor %}
                </div>


            </div>
            <!--Grid row-->


        </section>
        <!--/Section: Magazine v.1-->


    </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/base.html
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% block title %}

  {% endblock title %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!--  Stylesheet-->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>

{% include 'navbar.html' %}


{% block content %}

{% endblock content %}


{% include 'footer.html' %}


</body>

</html>

templates/bushcraftable.html
{% extends 'base.html' %}

{% block title %}
<title>Bushcraftable</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">


        <hr class="my-5">

        <!--Section: Magazine v.1-->
        <section class="wow fadeIn">

            <!--Section heading-->
            <h2 class="h1 text-center my-5 font-weight-bold">Bushcraftable - Tasty News</h2>

            <!--Grid row-->
            <div class="row text-left">

                <!--Grid column-->
                <div class="col-lg-6 col-md-12 h-100">

                    {% for element in data %}
                    <!--Small news-->
                    <div class="row">
                        <div class="col-md-3">

                            <!--Image-->
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid" alt="Minor sample post image">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>

                        <!--Excerpt-->
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>
                        </div>
                    </div>
                    <!--/Small news-->
                    <hr>
                    {% endfor %}
                </div>

            </div>
            <!--Grid row-->

        </section>
        <!--/Section: Magazine v.1-->

    </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/computer_world_news.html
{% extends 'base.html' %}

{% block title %}
<title>Computer World</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">


        <hr class="my-5">

        <!--Section: Magazine v.1-->
        <section class="wow fadeIn">

            <!--Section heading-->
            <h2 class="h1 text-center my-5 font-weight-bold">Computer World - Tasty News</h2>

            <!--Grid row-->
            <div class="row text-left">

                <!--Grid column-->
                <div class="col-lg-6 col-md-12 h-100">

                    {% for element in computer_world_data %}
                    <!--Small news-->
                    <div class="row">
                        <div class="col-md-3">

                            <!--Image-->
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid" alt="Minor sample post image">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>

                        <!--Excerpt-->
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>

                        </div>

                    </div>
                    <!--/Small news-->

                    <hr>
                    {% endfor %}
                </div>


            </div>
            <!--Grid row-->


        </section>
        <!--/Section: Magazine v.1-->


    </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-2">
        <h5>Tasty News</h5>
    </div>
    <!--/.Call to action-->

    <hr class="my-1">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/mateusz.wrobel.796/" target="_blank">
            <i class="fab fa-facebook-f mr-3 scale-on"></i>
        </a>

        <a href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w?view_as=subscriber" target="_blank">
            <i class="fab fa-youtube mr-3 scale-on"></i>
        </a>

        <a href="https://github.com/mateuszwwwrobel" target="_blank">
            <i class="fab fa-github mr-3 scale-on"></i>
        </a>

    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
        ©
        <script>document.write(new Date().getFullYear())</script>
        Copyright:
        <a href="https://github.com/mateuszwwwrobel" target="_blank"> Mateusz Wrobel</a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/homepage.html
{% extends 'base.html' %}
{% load static%}

{% block title %}
<title>Tasty News</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-4 pt-4">
    <div class="container">

        <section class="wow fadeIn">

            <!--Section heading-->
            <h2 class="h1 text-center mt-5 font-weight-bold">Tasty News</h2>

            {% if messages %}
            {% for message in messages %}
            <h2 class="h4 text-center text-danger my-3 font-weight-bold">{{ message }}</h2>
            {% endfor %}
            {% endif %}

            <!--Grid row-->
            <div class="row-modify text-left mb-5">

                <div class="list-group col-md-6 mt-2 ">

                    <div class="list-group-item list-group-item-action list-group-item-dark">
                        <img src="{% static 'img/ENG.webp' %}" class="float-left ml-1">
                    </div>

                    <a href="{% url 'core:bgg' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-dice mr-3"></i>Board Games Geek </a>

                    <a href="{% url 'core:python' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fab fa-python mr-3"></i>Info World - Python </a>

                    <a href="{% url 'core:real-python' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fab fa-python mr-3"></i>Real Python</a>

                    <a href="{% url 'core:livescience' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-atom mr-3"></i>LiveScience</a>

                    <div class="list-group-item list-group-item-action list-group-item-dark"></div>

                </div>

                <div class="list-group col-md-6 mt-2">

                    <div class="list-group-item list-group-item-action list-group-item-dark">
                        <img src="{% static 'img/PL.webp' %}" class="float-left ml-1">
                    </div>

                    <a href="{% url 'core:computer-world' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-laptop mr-3"></i></i>Computer World</a>

                    <a href="{% url 'core:benchmark' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-tv mr-3"></i>Benchmark</a>

                    <a href="{% url 'core:archeology' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-landmark mr-3"></i>Zwiadowca Historii</a>

                    <a href="{% url 'core:tojuzbylo' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-monument mr-3"></i>To Już Było!</a>

                    <a href="{% url 'core:lowcygier' %}"
                       class="list-group-item list-group-item-action list-group-item-primary"><i
                            class="fas fa-monument mr-3"></i>Łowcy Gier</a>

                    <div class="list-group-item list-group-item-action list-group-item-dark"></div>

                </div>

            </div>
            <!--Grid row-->
        </section>
    </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/livescience.html
{% extends 'base.html' %}

{% block title %}
<title>LiveScience</title>
{% endblock title %}

{% block content %}
<main class="mt-5 pt-5">
    <div class="container">
        <hr class="my-5">
        <section class="wow fadeIn">
            <h2 class="h1 text-center my-5 font-weight-bold">LiveScience - Tasty News</h2>
            <div class="row text-left">
                <div class="col-lg-6 col-md-12 h-100">
                    {% for element in data %}
                    <div class="row">
                        <div class="col-md-3">
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock content %}

templates/lowcygier.html
{% extends 'base.html' %}

{% block title %}
<title>Łowcy Gier</title>
{% endblock title %}

{% block content %}
<main class="mt-5 pt-5">
    <div class="container">
        <hr class="my-5">
        <section class="wow fadeIn">
            <h2 class="h1 text-center my-5 font-weight-bold">Łowcy Gier - Tasty News</h2>
            <div class="row text-left">
                <div class="col-lg-6 col-md-12 h-100">
                    {% for element in data %}
                    <div class="row">
                        <div class="col-md-3">
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock content %}

templates/navbar.html
<!--Main Navigation-->
<header>

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">
            <div class="float-left">
                <!-- Brand -->
                <a class="navbar-brand waves-effect mr-4 scale-on" href="{% url 'core:home' %}">
                    <strong class="blue-text">Tasty News</strong>
                </a>
                <a class="navbar-brand waves-effect scale-on" href="{% url 'core:statistics' %}">
                    <strong class="blue-text">Statistics</strong>
                </a>
            </div>
            <div class="float-right">
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        <a href="https://github.com/mateuszwwwrobel/"
                           class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-github scale-on"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.facebook.com/mateusz.wrobel.796/" class="nav-link waves-effect"
                           target="_blank">
                            <i class="fab fa-facebook-f scale-on"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.youtube.com/channel/UCqbh_cQEJo81E6RvjHllU5w?view_as=subscriber"
                           class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-youtube scale-on"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar -->

</header>
<!--Main Navigation-->

templates/real_python.html
{% extends 'base.html' %}

{% block title %}
<title>Real Python</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">


        <hr class="my-5">

        <!--Section: Magazine v.1-->
        <section class="wow fadeIn">

            <!--Section heading-->
            <h2 class="h1 text-center my-5 font-weight-bold">Real Python - Tasty News</h2>

            <!--Grid row-->
            <div class="row text-left">

                <!--Grid column-->
                <div class="col-lg-6 col-md-12 h-100">

                    {% for element in data %}
                    <!--Small news-->
                    <div class="row">
                        <div class="col-md-3">

                            <!--Image-->
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid" alt="Minor sample post image">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>

                        <!--Excerpt-->
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>
                        </div>
                    </div>
                    <!--/Small news-->
                    <hr>
                    {% endfor %}
                </div>

            </div>
            <!--Grid row-->

        </section>
        <!--/Section: Magazine v.1-->

    </div>
</main>
<!--Main layout-->


{% endblock content %}

templates/script.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="{% static "js/main.js" %}"></script>

templates/statistics.html
{% extends 'base.html' %}

{% block title %}
<title>Statistics</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">
        <hr>
        <section class="wow fadeIn">

            <!--Section heading-->
            <h3 class="h2 text-center my-5 font-weight-bold">Statistics - Tasty News</h3>

            <div class="row-modify text-left mb-5">

                <div class="list-group col-md-6 mt-2 ">

                    <!--Pie chart-->
                    <div style="width: 100%;">
                        <canvas id="articles-pie-chart" data-url="{% url 'core:chart-1' %}"></canvas>
                    </div>

                </div>

                <div class="list-group col-md-6 mt-2">

                    <!--Pie chart-->
                    <div style="width: 100%;">
                        <canvas id="articles-bar-chart" data-url="{% url 'core:chart-2' %}"></canvas>
                    </div>

                </div>

            </div>
            <hr>
            <div class="row-modify text-left mb-5">

                <div class="list-group col-md-6 mt-2 ">

                    <!--Pie chart-->
                    <div style="width: 100%;">
                        <canvas id="top-en-word-chart" data-url="{% url 'core:chart-3' %}"></canvas>
                    </div>

                </div>

                <div class="list-group col-md-6 mt-2">

                    <!--Pie chart-->
                    <div style="width: 100%;">
                        <canvas id="top-pl-word-chart" data-url="{% url 'core:chart-4' %}"></canvas>
                    </div>

                </div>

            </div>
            <hr>

        </section>
        <!--/Section: Magazine v.1-->

    </div>
</main>
<!--Main layout-->

{% include 'script.html' %}
{% endblock content %}

templates/tojuzbylo.html
{% extends 'base.html' %}

{% block title %}
<title>To już było</title>
{% endblock title %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-5">
    <div class="container">


        <hr class="my-5">

        <!--Section: Magazine v.1-->
        <section class="wow fadeIn">

            <!--Section heading-->
            <h2 class="h1 text-center my-5 font-weight-bold">To już było - Tasty News</h2>

            <!--Grid row-->
            <div class="row text-left">

                <!--Grid column-->
                <div class="col-lg-6 col-md-12 h-100">

                    {% for element in data %}
                    <!--Small news-->
                    <div class="row">
                        <div class="col-md-3">

                            <!--Image-->
                            <div class="view overlay rounded z-depth-1">
                                <img src="{{ element.2 }}" class="img-fluid" alt="Minor sample post image">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        </div>

                        <!--Excerpt-->
                        <div class="col-md-9 mt-3">
                            <a target="_blank" href="{{ element.0 }}">
                                <p class="h6"><i class="pr-2 fas fa-link"></i>{{ element.1 }}</p>
                            </a>

                        </div>

                    </div>
                    <!--/Small news-->

                    <hr>
                    {% endfor %}
                </div>


            </div>
            <!--Grid row-->


        </section>
        <!--/Section: Magazine v.1-->


    </div>
</main>
<!--Main layout-->


{% endblock content %}